[[headers]]
  for = "/*" # Wende diese Header auf alle Pfade an (z.B. /getMostPopular)
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:5173"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"